apiVersion: v1
kind: Service
metadata:
  name: ci-svc
  labels:
    app: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - name: ci-port
    protocol: TCP
    port: 80
    targetPort: 80