apiVersion: apps/v1
kind: Deployment
metadata:
  name: roll-deploy
  labels:
    stat: rool
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1
  selector:
    matchLabels:
      stat: rool
  template:
    metadata:
      name: roll-template
      labels:
        stat: rool
    spec:
      containers:
      - name: nginx-cont
        image: nginx:latest
        ports:
        - containerport: 80
...
---
apiVersion: v1
kind: Service
metedata:
  name: roll-svc
  labels:
    stat: rool
spec:
  type: NodePort
  selector:
    stat: rool
  ports:
    port: 80
    targetPort: 80

