apiVersion: v1
kind: Secret
metadata:
  name: my-secrete
  labels: 
    app: myapp
data:
  mysql_root_password: cm9vdDEyM0A=
  mysql_user: YWRtaW4=
  mysql_password: YWRtaW4xMjNA
  mysql_database: c3R1ZGVudERC